// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7NBmy0xKaBSmizBnGpJlrNOO5VOq8Vkw',
    appId: '1:232251227512:web:d43b0991dc745ef169dc8d',
    messagingSenderId: '232251227512',
    projectId: 'shoppinglists-64420',
    authDomain: 'shoppinglists-64420.firebaseapp.com',
    storageBucket: 'shoppinglists-64420.firebasestorage.app',
    measurementId: 'G-2B59T1PH5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDffbkRmpgDdxUuibdYvkfgAX9QRYYLnoo',
    appId: '1:232251227512:android:846b46b33b548b7369dc8d',
    messagingSenderId: '232251227512',
    projectId: 'shoppinglists-64420',
    storageBucket: 'shoppinglists-64420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz-vTRs_5NIULmzH-YmwWeUwtXLLxfSQI',
    appId: '1:232251227512:ios:a3ad7759750ba55169dc8d',
    messagingSenderId: '232251227512',
    projectId: 'shoppinglists-64420',
    storageBucket: 'shoppinglists-64420.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz-vTRs_5NIULmzH-YmwWeUwtXLLxfSQI',
    appId: '1:232251227512:ios:a3ad7759750ba55169dc8d',
    messagingSenderId: '232251227512',
    projectId: 'shoppinglists-64420',
    storageBucket: 'shoppinglists-64420.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7NBmy0xKaBSmizBnGpJlrNOO5VOq8Vkw',
    appId: '1:232251227512:web:3c57a2bf1db0059b69dc8d',
    messagingSenderId: '232251227512',
    projectId: 'shoppinglists-64420',
    authDomain: 'shoppinglists-64420.firebaseapp.com',
    storageBucket: 'shoppinglists-64420.firebasestorage.app',
    measurementId: 'G-THCE5TJSFM',
  );
}
